services:
  db:
    image: postgres:16.3
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - .docker/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbuserpass
    healthcheck :
      test: [ "CMD", "pg_isready", "-q", "-d", "db", "-U", "dbuser" ]
      interval : 1s
      timeout : 3s
      retries : 20
    networks:
      - my-app-network
  dbmigration:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile-migration
    restart: no
    environment:
      DATABASE_URL: postgres://dbuser:dbuserpass@db:5432/db
    networks:
      - my-app-network
  adminer:
    depends_on:
      db:
        condition: service_healthy
    image: adminer:standalone
    environment:
      - ADMINER_DESIGN=nette
      - ADMINER_PLUGINS=tables-filter tinymce    
      - ADMINER_DEFAULT_SERVER=db
    restart: always
    ports:
      - 9081:8080
    networks:
      - my-app-network

networks:
  my-app-network:
    driver: bridge
