services:
  db:
    image: postgres:16.3
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./.docker/db:/data/postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbuserpass
    networks:
      - my-app-network
  adminer:
    depends_on: 
      - db
    image: adminer:standalone
    restart: always
    ports:
      - 9081:8080
    networks:
      - my-app-network
      
networks:
  my-app-network:
    driver: bridge
